### ISSUE TITLE
21.Checklist de evaluación 

### ISSUE THREAD

**Issue by Deby93** [Deby93/2C-2023-Foro-PNT1-LANDA#21]
**General**⚙️

- [x] Logo

- [x] Información institucional

- [x] Contenido anónimo

- [x] Top 5 Entradas - Mas recientes

- [x] Top 5 Entradas - Con más preguntas y respuestas

- [x] Top 3 Miembros - Con más entradas cargadas en el último mes

- [x] Navegación por categorías

- [x] Pueden navegar por el foro en entradas públicas

- [x] Restricción a entradas privadas.  
Los miembros no habilitados pueden solicitar que se los habilite. Un miembro autor de la entrada, podrá ver un listado de miembros que quieren ser habilitados, y habilitarlos uno por uno. Al acceder a una entrada, se deberá mostrar las preguntas, en orden descendente por cantidad de likes recibidos.

- [x] Restricciones por Sesiones y Roles

- [x] Persistencia en SQL LocalDB

- [x] Inicialización de DB

 

**Miembro** 🥸

- [x] Auto registración con Rol

- [x] Inicio Sesión

- [x] Actualizar datos contacto, Dirección y teléfono

- [x] No modificar Email, DNI, Nombre, Apellido, etc.

- [x] No pueden eliminar entradas

- [x] Crear entrada y automáticamente generar una pregunta

- [x] Al crear una entrada, se ofrecerá también la posibilidad de crear una categoría, si las existentes no fuesen suficientes.

- [x] En caso de crearse, se debe volver a la creación de la entrada.

- [x] Desactivar preguntas

- [x] Preguntas desactivadas, deben poder ser vistas

- [x] Preguntas desactivadas, inhabilita a agregar respuestas.

- [x] No puede responder a sus propias preguntas

- [x]  Puede crear categorías. Se debe suministrar un listado existente en orden alfabético previamente.

- [x] Se puede reaccionar a las respuestas que no son de uno mismo.

- [x] Reaccion - Like / Dislike / Reset

- [x] MisEntradas - Listadas cronológico descendentes

- [x] Cada entrada lista preguntas en orden descendente por cantidad de likes.

- [x] Cada pregunta mostrará al costado la cantidad de respuestas recibidas.

- [x] Se puede crear múltiples preguntas en una entrada por el mismo miembro.

- [x] Al acceder a cada pregunta, se listaran las respuestas en orden cronológico ascendente.

- [x] No puede crear una respuesta, el creador de la pregunta.

- [x] La respuesta con más likes, deberá descartase visualmente. Ej. en verde.

- [x] La respuesta con más dislikes, deberá destacarse visualmente. Ej. en rojo

 

**Administrador**👑

- [x] Crear otro administrador con su rol correspondiente.

- [x] ABM Administradores

- [x] Password automática por sistema

- [x] Puede eliminar entradas con Dislike preguntas, y respuestas, en caso de contenido inapropiado.

- [x] No puede eliminar usuarios

 

**Restricciones / Generalidades** 🛡️

- [x] No se puede duplicar Categoria.Nombre

**Comment by Deby93** [comment]
@marianolongoort Hola profe termine el proyecto para poder rendir el final, te lo mando para ver si lo podes revisar para antes de rendir. Muchas gracias. Saludos. Débora Landa.

**Comment by marianolongoort** [comment]
@Deby93 dale, perfecto, nos vemos el Lunes 8. Exitos.

**Comment by marianolongoort** [comment]
@Deby93 solo un comentario rápido. Levantá el proyecto, presioná Registrarte y luego sin ingresar info, Registrar. 😮

**Comment by Deby93** [comment]
@marianolongoort gracias por avisar! No lo habia visto eso.

**Comment by Deby93** [comment]
@marianolongoort  Hola Mariano, como va? ahi modifique se crea la base no tira el mismo error pero esta re roto. No se si llego al final. Tengo error ahora para crear el usuario miembro, replique lo que hace la precarga pero no lo logre aun... todo lo demas lo probe y no esta mal creo yo, pero esto no lo logro sacar todavia.  Gracias. Saludos

**Comment by marianolongoort** [comment]
@Deby93 estaba ok el proyecto. Solo te lo pasé para que revises ese.
Nos vemos el lunes.

**Comment by Deby93** [comment]
@marianolongoort bueno perfecto, trato de resolver ese punto. Nos vemos el lunes. Muchas gracias
