### ISSUE TITLE
01.Planificación

### ISSUE THREAD

**Issue by Deby93** [Deby93/2C-2023-Foro-PNT1-LANDA#5]
**Todos los integrantes:**
- [x] Definir que integrante es 1️⃣2️3️ y 4️⃣
Modelos
- [x] Definición de clases a crear
- [x] Repartirse las clases por integrante
Propiedades
- [x] Definir relación y cardinalidad entre clases (idea inicial)
- [x] Definir dependencias
