### ISSUE TITLE
08.Planificación

### ISSUE THREAD

**Issue by Deby93** [Deby93/2C-2023-Foro-PNT1-LANDA#8]
**Todos los integrantes:**
- [x] Revisión, Distribuir tareas y remediar según Feedback anterior
- [x] Imaginar interacción del usuario con el sistema - modalidad de uso, asistente (Wizard, paso a paso), AIO (All-InOne). Básicamente si se quiere que el usuario cargue todo en un único formulario de una vez cuando sea posible, o el
sistema lo va guiando por pantallas, carga datos, siguiente, así sucesivamente. No obstante, considerar las
funcionalidades que se piden en el enunciado. Si indica modo wizard, debe respetarse.
- [x] Definición inicial de interfaz, componentes y texto participante
- [x] Repartirse tareas
